name: Check Dependencies Reminder

on:
  schedule:
    - cron: '0 8 1 1 *'  # 1er janvier à 08:00 UTC
    - cron: '0 8 1 7 *'  # 1er juillet à 08:00 UTC
  workflow_dispatch:      # Permet aussi un lancement manuel

jobs:
  create-reminder-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Créer un rappel de vérification des dépendances
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: 📦 Vérification semestrielle des dépendances
          content-filepath: .github/dependency-reminder.md
          labels: maintenance, dependencies
          token: ${{ secrets.GITHUB_TOKEN }}
